name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Restore dependencies
      run: dotnet restore BufferQueue.slnx
    - name: Build
      run: dotnet build BufferQueue.slnx --no-restore
    - name: Format
      run: dotnet format BufferQueue.slnx --verify-no-changes --verbosity diagnostic
    - name: Test
      run: dotnet test BufferQueue.slnx -c Release --collect:"XPlat Code Coverage"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
